const WINDOW_RESIZE = 'WINDOW_RESIZE';

const NAV_TOGGLE_MENU = 'NAV_TOGGLE_MENU';

const UPDATE_INSTANCE_INFO = 'UPDATE_INSTANCE_INFO';

export default {WINDOW_RESIZE, NAV_TOGGLE_MENU, UPDATE_INSTANCE_INFO};
